name: Playwright Tests
on:
  # push:
  #  branches: [ main, master ]
  # pull_request:
  #  branches: [ main, master ]
  workflow_dispatch:
   inputs:
      userRepo:
      devMatchSubmissionId:
        required: true
      home:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: devMatchSubmissionId:${{ inputs.devMatchSubmissionId }}
      run: echo devmatch identifier is ${{ inputs.devMatchSubmissionId }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: echo "Repo to pull from ${{ github.event.inputs.userRepo }}"
    - run: git remote add devmatch ${{ github.event.inputs.userRepo }}
    - run: git fetch --all
    - run: git pull --rebase devmatch main 
    - name: Install dependencies
      run: npm ci
    - name: Launch web server
      run: ./node_modules/http-server/bin/http-server &
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2
