name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
   inputs:
      name:
      home:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: echo "MESSAGE - ${{ github.event.inputs.message }} "
    - run: git remote add devmatch ${{ github.event.inputs.message }}
    - run: git fetch --all
    - run: git pull devmatch main
    - name: Install dependencies
      run: npm ci
    - name: Launch web server
      run: ./node_modules/http-server/bin/http-server &
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2
